### ISSUE TITLE
Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found

### ISSUE THREAD

**Issue by Jan-Olof** [codemillmatt/forms-ad-b2c#1]
We cloned the repository and built the "2-add-ad-b2c" solution without problems. 

Then we started the Android project and right away we got this exception:

Unhandled Exception:

System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found. Occurred

![missing-method-exception](https://user-images.githubusercontent.com/4889664/33659052-17450c18-da7f-11e7-90a4-68e4721d1bbb.png)

Unfortunately we could not get any further after this.

**Comment by codemillmatt** [comment]
Thanks for grabbing the repo! (I haven't even officially published the accompanying blog post yet! 😄 )

Unfortunately the Microsoft.Client.Identity library in it's current state throws an exception in Android that has support libraries 25.x and above. 

There's a hotfix coming for it next week: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/490

**Comment by Jan-Olof** [comment]
Great, thanks a lot for the info! 

Also thanks for your really good blog posts. Helped our team a lot. It was really nice when we found the final post in the repo yesterday as well. 😄
